name: Update README on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_readme_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract PR Information
        id: pr_info
        run: |
          echo "PR_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_TIME=$(date)" >> $GITHUB_ENV

      - name: Update README
        run: |
          echo "### Pull Request Details" > README.md
          echo "- **Branch**: $PR_BRANCH" >> README.md
          echo "- **Base Branch**: $BASE_BRANCH" >> README.md
          echo "- **Title**: $PR_TITLE" >> README.md
          echo "- **Time**: $PR_TIME" >> README.md

      - name: Commit and Push Changes
        run: |
          git checkout ${{ github.head_ref }}
          git add README.md
          git commit -m "Update README with PR details"
          git push origin ${{ github.head_ref }}
