name: Update README in Feature Branch

on:
  push:
    branches:
      - branch1

jobs:
  update_readme_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update README
        run: |
          echo "Hello from branch1! Updated on $(date)" > README.md

      - name: Commit and push changes
        run: |
          git checkout -b feature/update-readme
          git add README.md
          git commit -m "Update README from branch1"
          git push origin feature/update-readme --force
